apiVersion: apps/v1
kind: Deployment
metadata:
  name: icap-accountservice-deployment
  labels:
    app: icap-accountservice-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icap-accountservice
  template:
    metadata:
      labels:
        app: icap-accountservice
    spec:
      containers:
        - name: icap-accountservice
          image: icapacr.azurecr.io/icap-accountservice:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store-accountservice
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-accountservice
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "icap-accountservice-kv"