apiVersion: apps/v1
kind: Deployment
metadata:
  name: icap-accountservice
  labels:
    app: icap-accountservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: icap-accountservice
  template:
    metadata:
      labels:
        app: icap-accountservice
    spec:
      containers:
      - name: icap-accountservice
        image: icapacr.azurecr.io/icap-accountservice:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: secrets-store-accountservice
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-accountservice
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "icap-accountservice-kv"