apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icap-accountservice
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: icap-accountservice
            port: 
              number: 5000