apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icap-accountservice-ingress
  namespace: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: aks.odb-tech.com
    http:
      paths:
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: icap-accountservice
            port: 
              number: 5000
  