apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: https://icap-vault.vault.azure.net/certificates/ICAP-TEST-CERT/5254f0f9ecea4910bbd257fbcb9862de    
  name: icap-accountservice
  namespace: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: icap.com
    http:
      paths:
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: icap-accountservice
            port: 
              number: 80
  tls:
  - hosts:
    - icap.com
    secretName: keyvault-icap-accountservice
  