apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: icap-accountservice-hpa
  namespace: default
spec:
  maxReplicas: 15
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: icap-accountservice
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 50
