apiVersion: v1
kind: Service
metadata:
  name: ICAP_AccountService
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ICAP_AccountService
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000