apiVersion: v1
kind: Service
metadata:
  name: icap-accountservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: icap-accountservice
  ports:
    - port: 5000
      targetport: 5000