apiVersion: v1
kind: Service
metadata:
  name: production
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: production
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000