apiVersion: apps/v1
kind: Deployment
metadata:
  name: icap-relationservice
  labels:
    app: icap-relationservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: icap-relationservice
  template:
    metadata:
      labels:
        app: icap-relationservice
    spec:
      containers:
      - name: icap-relationservice
        image: icapacr.azurecr.io/icap-relationservice:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: secrets-store-relationservice
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      volumes:
      - name: secrets-store-relationservice
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "icap-relationservice-kv"