apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icap-relationservice
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: icap-relationservice
          servicePort: 5200