apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icap-relationservice
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host:
    http:
      paths:
      - path: /relations
        pathType: Prefix
        backend:
          service:
            name: icap-relationservice
            port: 
              number: 5200