kind: Pod
apiVersion: v1
metadata:
  name: quick-start
  namespace: default
spec:
  containers:
    - name: icap-relationservice
      image: icapregistry.azurecr.io/icap-relationservice:latest      
      volumeMounts:
      - name: secrets-store-relationservice
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store-relationservice
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "icap-relationservice-kv"