apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: icap-relationservice-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"       
    clientID: "2df15af9-7447-4900-b35c-bd6bf40cc47b" # Setting this to use workload identity
    keyvaultName: "ICAPVault"
    objects:  |   # object types: secret, key, or cert
      array:
        - |
          objectName: AzureServiceBus
          objectType: secret
        - |
          objectName: MongoDBSettings
          objectType: secret
    tenantId: "d5c5f66e-eb0a-4d32-a625-bf18569a40f9"