apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: icap-relationservice-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   
    userAssignedIdentityID: "8af6dc77-db48-49c0-90a2-51ef6b0eba2d"
    keyvaultName: "ICAP-Vault"
    objects:  |
      array:
        - |
          objectName: AzureServiceBus
          objectType: secret
        - |
          objectName: MongoConnectionString
          objectType: secret
        - |
          objectName: MongoDatabaseName
          objectType: secret
    tenantId: "d5c5f66e-eb0a-4d32-a625-bf18569a40f9"