apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: icap-relationservice-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   
    clientID: "9d601ded-d677-48f8-bdf5-6f27d55d2ce2"
    keyvaultName: "ICAPVault"
    objects:  |
      array:
        - |
          objectName: AzureServiceBus
          objectType: secret
        - |
          objectName: MongoConnectionString
          objectType: secret
        - |
          objectName: MongoDatabaseName
          objectType: secret
    tenantId: "d5c5f66e-eb0a-4d32-a625-bf18569a40f9"