apiVersion: v1
kind: Service
metadata:
  name: icap-relationservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: icap-relationservice
  ports:
    - port: 5000
      targetPort: 5000