apiVersion: v1
kind: Service
metadata:
  name: icap-relationservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: icap-relationservice
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002