apiVersion: v1
kind: Service
metadata:
  name: ICAP_RelationService
  namespace: ICAP
spec:
  type: LoadBalancer
  selector:
    app: ICAP_RelationService
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002