apiVersion: apps/v1
kind: Deployment
metadata:
  name: icap-marketService
  labels:
    app: icap-marketService
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icap-marketService
  template:
    metadata:
      labels:
        app: icap-marketService
    spec:
      containers:
        - name: icap-marketService
          image: icap-marketService:latest
          ports:
            - containerPort: 80