apiVersion: apps/v1
kind: Deployment
metadata:
  name: icap-marketservice
  labels:
    app: icap-marketservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: icap-marketservice
  template:
    metadata:
      labels:
        app: icap-marketservice
    spec:
      containers:
      - name: icap-marketservice
        image: icapacr.azurecr.io/icap-marketservice:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: secrets-store-marketservice
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources:
          requests:
            cpu: 1m
          limits:
            cpu: 500m
      volumes:
      - name: secrets-store-marketservice
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "icap-marketservice-kv"