apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icap-marketservice
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: icap-marketservice
          servicePort: 5100