apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icap-marketservice
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
    host: aks.odb-tech.com
      paths:
      - path: /market
        pathType: Prefix
        backend:
          service:
            name: icap-marketservice
            port: 
              number: 80