kind: Pod
apiVersion: v1
metadata:
  name: quick-start
  namespace: default
spec:
  containers:
    - name: icap-marketservice
      image: icapregistry.azurecr.io/icap-marketservice:latest      
      volumeMounts:
      - name: secrets-store-marketservice
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: 
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "icap-marketservice-kv"