apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: icap-marketservice-hpa
spec:
  maxReplicas: 15
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: icap-marketservice
    metrics: 50 # target CPU utilization
