apiVersion: v1
kind: Service
metadata:
  name: icap-marketservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: icap-marketservice
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80