apiVersion: v1
kind: Service
metadata:
  name: ICAP_MarketService
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ICAP_MarketService
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80